#include "autogen.hpp"
#include "override/prototype_light.inl"
#include "override/reflector_light.inl"
#include "autogen_prototype_light_data.inl"
#include "autogen_reflector_light_data.inl"
#include "autogen_prototype_camera.inl"
#include "autogen_reflector_camera.inl"
